### PR TITLE
[Feature] Bootstrap and other templates support

### PR DESCRIPTION
**Pull request by seccomiro**
If applied this PR will allow users to choose between regular (the old way) view templates and Bootstraped views.

The feature was designed in a way it could be reused for other custom template styles.

Although a working example of `authLayout.edge` has been provided, it needs to be improved for production purposes. We assume that the user knows to how to configure (or have already done it) Bootstrap in his app.

### CODE REVIEW

**Comment by seccomiro** [comment]
If you accept all my PRs in the order I made them, you'll experience a conflict inside `MakeAuth._copyFiles()` function, because of #15.

The right merge is a mix of both commits, keeping only the calls with arguments, as shown below:

```javascript
await this.copyPartialsViewTemplates(stylePath)
await this.copyAuthViewTemplates(stylePath)
await this.copyLayoutViewTemplates(stylePath)
await this.copyAppStarterFiles(client)
```

**Comment by creatrixity** [comment]
I'm currently previewing the PR.

**Comment by creatrixity** [comment]
Thanks for all the Pulls. They've been timely. Time for a new NPM release.

**Comment by seccomiro** [comment]
Hey. Thank you for all the merges, but I think you didn't pay attention to the message above and you forgot to keep the last line:
```javascript
await this.copyAppStarterFiles(client) // the branch is still without the argument
```
This way, #15 were totally overwritten.
I'll open a new PR with this updated.

**Pull request merged**
